// Generate the split-template seed from the app's SplitPreset data (transcribed
// from WorkoutSplit.swift). Each preset's days get a day_type mapped from their
// name, so day recipes plug in. Body-part/bro days with no matching recipe get
// day_type null — author a recipe and tag them in the dashboard.
//
//   node scripts/extract-splits.mjs   →   ../pumpdeck/supabase/migrations/0104_split_seed.sql

import { writeFileSync } from 'fs';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = `${HERE}/../../pumpdeck/supabase/migrations/0104_split_seed.sql`;

const C = 'chest', B = 'back', S = 'shoulders', L = 'legs', CO = 'core', BI = 'biceps', TR = 'triceps', F = 'forearms';
const ALL = [C, B, S, L, CO, BI, TR, F];
const UPPER = [C, B, S, BI, TR, F];
const PUSH = [C, S, TR];
const PULL = [B, BI, F];
const LC = [L, CO];
const ARMS4 = [BI, TR, S, F];
const ARMS3 = [BI, TR, F];

const DAY_TYPE = {
  'Full Body': 'full', Upper: 'upper', Lower: 'lower',
  'Push Day': 'push', 'Pull Day': 'pull', 'Leg Day': 'legs', 'Arm Day': 'arms', 'Upper Day': 'upper',
};

// [key, label, blurb, days, sortOrder, [ [weekday, dayName, groups], ... ]]
const presets = [
  ['twoFullBody', '2-day Full Body', 'Whole body each session, twice a week', 2, 0, [[2, 'Full Body', ALL], [5, 'Full Body', ALL]]],
  ['twoUpperLower', '2-day Upper / Lower', 'Upper one day, lower the other', 2, 1, [[2, 'Upper', UPPER], [5, 'Lower', LC]]],
  ['threeFullBody', '3-day Full Body', 'Whole body 3× — best frequency for beginners', 3, 2, [[2, 'Full Body', ALL], [4, 'Full Body', ALL], [6, 'Full Body', ALL]]],
  ['threePPL', '3-day Push / Pull / Legs', 'Focused days, each muscle once a week', 3, 3, [[2, 'Push Day', PUSH], [4, 'Pull Day', PULL], [6, 'Leg Day', LC]]],
  ['threeUpperLowerFull', '3-day Upper / Lower / Full', 'Two splits plus one full-body day', 3, 4, [[2, 'Upper', UPPER], [4, 'Lower', LC], [6, 'Full Body', ALL]]],
  ['fourUpperLower', '4-day Upper / Lower', 'Every muscle 2×/week — balanced go-to', 4, 5, [[2, 'Upper', UPPER], [3, 'Lower', LC], [5, 'Upper', UPPER], [6, 'Lower', LC]]],
  ['fourPPLArms', '4-day Push / Pull / Legs / Arms', 'Focused days with a dedicated arm day', 4, 6, [[2, 'Push Day', PUSH], [3, 'Pull Day', PULL], [5, 'Leg Day', LC], [6, 'Arm Day', ARMS4]]],
  ['fourBodyPart', '4-day Body Part', 'Fewer muscles per day, shorter sessions', 4, 7, [[2, 'Chest & Triceps', [C, TR]], [3, 'Back & Biceps', [B, BI, F]], [5, 'Shoulders & Core', [S, CO]], [6, 'Leg Day', [L]]]],
  ['fivePPLUL', '5-day Push / Pull / Legs / Upper / Lower', 'Push/pull/legs plus two balanced days', 5, 8, [[2, 'Push Day', PUSH], [3, 'Pull Day', PULL], [4, 'Leg Day', LC], [5, 'Upper', UPPER], [6, 'Lower', LC]]],
  ['fiveUpperLowerPPL', '5-day Upper / Lower / PPL', 'Upper/lower plus push/pull/legs', 5, 9, [[2, 'Upper', UPPER], [3, 'Lower', LC], [4, 'Push Day', PUSH], [5, 'Pull Day', PULL], [6, 'Leg Day', LC]]],
  ['fiveBro', '5-day Bro split', 'One muscle group per day, focused sessions', 5, 10, [[2, 'Chest Day', [C]], [3, 'Back Day', [B]], [4, 'Shoulder Day', [S]], [5, 'Leg Day', LC], [6, 'Arm Day', ARMS3]]],
  ['sixPPL', '6-day PPL × 2', 'Push/pull/legs twice — high frequency', 6, 11, [[2, 'Push Day', PUSH], [3, 'Pull Day', PULL], [4, 'Leg Day', LC], [5, 'Push Day', PUSH], [6, 'Pull Day', PULL], [7, 'Leg Day', LC]]],
  ['sixArnold', '6-day Arnold split', 'Paired groups, each trained twice a week', 6, 12, [[2, 'Chest & Back', [C, B]], [3, 'Shoulders & Arms', [S, BI, TR, F]], [4, 'Leg Day', LC], [5, 'Chest & Back', [C, B]], [6, 'Shoulders & Arms', [S, BI, TR, F]], [7, 'Leg Day', LC]]],
  ['sevenBodyPart', '7-day Body Part', 'A body part every day of the week', 7, 13, [[2, 'Chest Day', [C]], [3, 'Back Day', [B]], [4, 'Shoulder Day', [S]], [5, 'Leg Day', [L]], [6, 'Arm Day', [BI, TR]], [7, 'Core Day', [CO, F]], [1, 'Upper Day', [C, B]]]],
  ['sevenPPLArms', '7-day PPL × 2 + Arms', 'Push/pull/legs twice plus an arm day', 7, 14, [[2, 'Push Day', PUSH], [3, 'Pull Day', PULL], [4, 'Leg Day', LC], [5, 'Push Day', PUSH], [6, 'Pull Day', PULL], [7, 'Leg Day', LC], [1, 'Arm Day', ARMS4]]],
];

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;

let sql = `-- Program-gen v2: seed content_split_templates from the app's SplitPreset data.
-- GENERATED by pumpdeck-admin/scripts/extract-splits.mjs. Idempotent.

`;
let untyped = 0;
for (const [key, label, blurb, days, sort, plan] of presets) {
  const dayAssignments = plan.map(([weekday, dayName, groups]) => {
    const dt = DAY_TYPE[dayName] ?? null;
    if (!dt) untyped++;
    return { weekday, day_name: dayName, day_type: dt, groups };
  });
  const json = JSON.stringify(dayAssignments).replace(/'/g, "''");
  sql += `insert into public.content_split_templates (key,display_name,blurb,min_days,max_days,day_assignments,sort_order) values (`
    + `${q(key)},${q(label)},${q(blurb)},${days},${days},'${json}'::jsonb,${sort}) on conflict (key) do nothing;\n`;
}

writeFileSync(OUT, sql);
console.log(`✓ ${presets.length} split templates → ${OUT}`);
console.log(`  ${untyped} days have no matching recipe yet (day_type null) — add recipes + tag them in the dashboard.`);
